#KONFIGURASI DATABASE DAN SERVER PORT

server:
  port: 10000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aplikasi_resource_server
    username: root
    password: root

---

spring:
  jpa:
    generate-ddl: true
    show-sql: true